name: "checkout"
description: "Checkout the repository with a specific commit of actions/checkout"
inputs:
  repository:
    description: "Repository name with owner. For example, actions/checkout"
    default: ${{ github.repository }}
    required: false
  ref:
    description: "The branch, tag or SHA to checkout"
    required: false
  fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    default: 1
    required: false
  sparse-checkout:
    description: "Do a sparse checkout on given patterns. Each pattern should be separated with new lines."
    required: false
  sparse-checkout-cone-mode:
    description: "Specifies whether to use cone-mode when doing a sparse checkout."
    default: true
    required: false
  token:
    description: "Personal access token (PAT) used to fetch the repository."
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
        sparse-checkout: ${{ inputs.sparse-checkout }}
        sparse-checkout-cone-mode: ${{ inputs.sparse-checkout-cone-mode }}
        token: ${{ inputs.token }}
