name: copilot-setup-steps

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ./.github/actions/checkout
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-python
      - name: pre-commit setup
        run: |
          uv pip install --system -r requirements/lint-requirements.txt
          dev/install-taplo.sh
          dev/install-typos.sh
          dev/install-conftest.sh
          pre-commit install --install-hooks
