name: Labeling

on:
  issues:
    types:
      - opened
      - edited
  pull_request_target:
    types:
      - opened
      - edited

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  labeling:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    timeout-minutes: 5
    steps:
      - uses: ./.github/actions/checkout
        with:
          sparse-checkout: |
            .github
      - uses: ./.github/actions/github-script
        with:
          script: |
            const script = require('./.github/workflows/labeling.js');
            await script({ github, context });
