name: Maintainer approval

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read
    steps:
      - uses: ./.github/actions/checkout
        with:
          sparse-checkout: |
            .github
      - name: Fail without core maintainer approval
        uses: ./.github/actions/github-script
        with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/require-core-maintainer-approval.js`);
            await script({ context, github, core });
