name: Patch

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  patch:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    timeout-minutes: 120
    steps:
      - uses: ./.github/actions/checkout
        with:
          sparse-checkout: |
            .github
      - uses: ./.github/actions/github-script
        with:
          script: |
            const script = require('./.github/workflows/patch.js');
            await script({ github, context, core });
